"""
StudyBuddy Mini - Prototype Backend Module
MindGarden Learning Systems

This module accepts a list of vocabulary words and returns:
- simple autogenerated definitions
- example sentences
- a small multiple-choice quiz

NOTE:
This is a demo version using simple rule-based generation.
In a production app, these would be replaced with AI-assisted generation.
"""
import random
from typing import List, Dict


# ------------------------------------------------------------
# 1. Simple definition generator
# ------------------------------------------------------------
def generate_definition(word: str) -> str:
    """
    Generates a kid-friendly placeholder definition.
    (Rule-based for prototype purposes)
    """
    return f"{word.capitalize()} means something related to '{word}' in a simple way."


# ------------------------------------------------------------
# 2. Simple example sentence generator
# ------------------------------------------------------------
def generate_example_sentence(word: str) -> str:
    """
    Generates a basic example sentence that includes the word.
    """
    return f"The student used the word '{word}' in a sentence to show they understood it."


# ------------------------------------------------------------
# 3. Quiz generator
# ------------------------------------------------------------
def generate_quiz(words: List[str]) -> List[Dict]:
    """
    Creates 3-4 multiple-choice questions.
    Each question has:
      - the word
      - the correct definition
      - 3 options total (1 correct, 2 distractors)
    """
    quiz_questions = []
    num_questions = min(len(words), random.randint(3, 4))
    sampled_words = random.sample(words, num_questions)

    for word in sampled_words:
        correct_def = generate_definition(word)
        distractors = [
            f"A random idea not related to {word}.",
            f"Something that sounds like {word} but means something different."
        ]
        options = [correct_def] + distractors
        random.shuffle(options)

        quiz_questions.append({
            "question": f"What is the meaning of '{word}'?",
            "options": options,
            "answer": correct_def  # frontend expects "answer" key
        })

    return quiz_questions


# ------------------------------------------------------------
# 4. Master function — maps to the API response shape the frontend expects
# ------------------------------------------------------------
def process_vocabulary(words: List[str]) -> Dict:
    """
    Takes a list of vocabulary words and returns:
      {
        "words": [{ "word", "definition", "example" }, ...],
        "quiz":  [{ "question", "options", "answer"  }, ...]
      }
    """
    output = {
        "words": [],
        "quiz": []
    }

    for word in words:
        entry = {
            "word": word.strip(),
            "definition": generate_definition(word.strip()),
            "example": generate_example_sentence(word.strip())
        }
        output["words"].append(entry)

    output["quiz"] = generate_quiz([w.strip() for w in words])
    return output


# ------------------------------------------------------------
# 5. Demo run (standalone test)
# ------------------------------------------------------------
if __name__ == "__main__":
    sample_words = ["brave", "curious", "observe", "compare", "bright"]
    result = process_vocabulary(sample_words)
    import json
    print(json.dumps(result, indent=2))
